version: "3.8"

services:

  tmdb:
    build: ./backend-services/tmdb
    container_name: tmdb
    command: go run main.go
    volumes:
      - ./backend-services/tmdb:/go/src/tmdb
    working_dir: /go/src/tmdb
    environment:
      PORT: 80
      API_KEY: ""

  frontend:
    build: ./frontend/
    container_name: frontend
    command: yarn dev
    volumes:
      - ./frontend:/usr/app
      - ./frontend/node_modules:/usr/app/node_modules
    ports:
      - 3000:80
    environment:
      PORT: 80

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/assets:/assets
    ports:
      - 80:80
    links:
      - frontend:frontend
      - tmdb:tmdb

    networks:
      default:
        aliases:
          - waffle.local.com

volumes:
  postgres-data:
